# Generated by Django 5.1.6 on 2025-02-06 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="phone_number",
            field=models.CharField(
                max_length=11, unique=True, verbose_name="Номер телефона"
            ),
        ),
    ]
