# Generated by Django 5.1.6 on 2025-02-11 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_app", "0003_log"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("на рассмотрении", "На рассмотрении"),
                    ("в работе", "В работе"),
                    ("просрочена", "Просрочена"),
                    ("выполнена", "Выполнена"),
                ],
                default="на рассмотрении",
                max_length=20,
                verbose_name="Статус заявки",
            ),
        ),
    ]
