services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: task_portal
      POSTGRES_USER: dergilev
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - app_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dergilev -d task_portal"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 config.wsgi:application
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: postgres://dergilev:admin@db:5432/task_portal
      CELERY_BROKER_URL: redis://redis:6379/0
    networks:
      - app_network

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    networks:
      - app_network

  celery:
    build: .
    command: celery -A config worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: postgres://dergilev:admin@db:5432/task_portal
      CELERY_BROKER_URL: redis://redis:6379/0
    networks:
      - app_network

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - web
    networks:
      - app_network

volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge