# Generated by Django 5.1.4 on 2025-01-26 12:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20, unique=True, verbose_name='Номер телефона')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Фамилия')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('platform_type', models.CharField(max_length=100, verbose_name='Тип площадки')),
                ('legal_entity', models.CharField(max_length=100, verbose_name='Юрлицо')),
                ('problem_description', models.TextField(verbose_name='Краткое описание проблемы')),
                ('problem_location', models.CharField(max_length=200, verbose_name='Место проблемы')),
                ('problem_type', models.CharField(max_length=100, verbose_name='Тип проблемы')),
                ('task_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата заявки')),
                ('task_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Номер заявки ID')),
                ('phone_number', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='my_app.users', verbose_name='Номер телефона')),
            ],
        ),
    ]
